# Generated by Django 4.2 on 2023-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('data_venc', models.DateField()),
                ('fornecedor', models.CharField(max_length=50)),
            ],
        ),
    ]
